export const HomeData = {
  ShopbyHealthConcerns: [
    {
      title: "Diabetes Care",
      path: "/medicines",
      img: "https://onemg.gumlet.io/a_ignore,w_150,h_150,c_fit,q_auto,f_auto/e3katuw3w1qdfiv0cbjn.png",
    },
    {
      title: "Cardiac Care",
      path: "/labTests",
      img: "https://onemg.gumlet.io/a_ignore,w_150,h_150,c_fit,q_auto,f_auto/bal76mxxccyhrti2erkn.png",
    },
    {
      title: "Stomach Care",
      path: "/healthcare",
      img: "https://onemg.gumlet.io/a_ignore,w_150,h_150,c_fit,q_auto,f_auto/l2zrxcsfyguccggnkp4m.png",
    },
    {
      title: "Liver Care",
      path: "/",
      img: "https://onemg.gumlet.io/a_ignore,w_150,h_150,c_fit,q_auto,f_auto/klrkvhzloqbyt6z8cvgv.png",
    },
    {
      title: "Bone, Joint & Muscle Care",
      path: "/",
      img: "https://onemg.gumlet.io/a_ignore,w_150,h_150,c_fit,q_auto,f_auto/zd1jcixlqcmxlxlmgitc.png",
    },
    {
      title: "Kidney Care",
      path: "/offers",
      img: "https://onemg.gumlet.io/a_ignore,w_150,h_150,c_fit,q_auto,f_auto/c0o3w8wdjnzesk2pshcr.png",
    },
    {
      title: "Pain Relief",
      path: "/",
      img: "https://onemg.gumlet.io/a_ignore,w_150,h_150,c_fit,q_auto,f_auto/vsyneobahnsdqzllvzuv.png",
    },
    {
      title: "Respiratory Care",
      path: "/",
      img: "https://onemg.gumlet.io/a_ignore,w_150,h_150,c_fit,q_auto,f_auto/wgixpbxnlrd79lzhpsi3.png",
    },
    {
      title: "Eye Care",
      path: "/",
      img: "https://onemg.gumlet.io/a_ignore,w_150,h_150,c_fit,q_auto,f_auto/laztovaqkws3bo1ywff0.png",
    },
  ],
  FeaturedBrands: [
    {
      title: "Dabur",
      path: "/medicines",
      img: "https://onemg.gumlet.io/a_ignore,w_150,h_150,c_fit…o,f_auto/0bc7a0c3-93ae-4902-9218-4c6585e62d2e.jpg",
    },
    {
      title: "Dr Willmar Schwabe India",
      path: "/labTests",
      img: "	https://onemg.gumlet.io/a_ignore,w_150,h_150,c_fit…o,f_auto/778eb34a-941b-4603-9c70-dd3d8513748e.jpg",
    },
    {
      title: "Cetaphil",
      path: "/healthcare",
      img: "https://onemg.gumlet.io/a_ignore,w_150,h_150,c_fit…o,f_auto/19bf12c2-01ba-4b47-a4cb-14a180072829.png",
    },
    {
      title: "Baidyanath",
      path: "/",
      img: "https://onemg.gumlet.io/a_ignore,w_150,h_150,c_fit…o,f_auto/14be97ad-0fa9-4f70-ba8c-18aa34ece123.png",
    },
    {
      title: "Iodex",
      path: "/",
      img: "https://onemg.gumlet.io/a_ignore,w_150,h_150,c_fit…o,f_auto/38f4de2d-dc12-4750-a2d9-4e1ebe5e0c2f.png",
    },
    {
      title: "Kidney Care",
      path: "/offers",
      img: "https://onemg.gumlet.io/a_ignore,w_150,h_150,c_fit,q_auto,f_auto/c0o3w8wdjnzesk2pshcr.png",
    },
    {
      title: "Pain Relief",
      path: "/",
      img: "https://onemg.gumlet.io/a_ignore,w_150,h_150,c_fit,q_auto,f_auto/vsyneobahnsdqzllvzuv.png",
    },
    {
      title: "Respiratory Care",
      path: "/",
      img: "https://onemg.gumlet.io/a_ignore,w_150,h_150,c_fit,q_auto,f_auto/wgixpbxnlrd79lzhpsi3.png",
    },
    {
      title: "Eye Care",
      path: "/",
      img: "https://onemg.gumlet.io/a_ignore,w_150,h_150,c_fit,q_auto,f_auto/laztovaqkws3bo1ywff0.png",
    },
  ],
  TopSellersFromZandu: [
    {
      isProduct: true,
      title: "Zandu Kesari Jeevan Fit for Diabetics",
      path: "/medicines",
      desc: "jar of 900 gm Paste",
      price: 655,
      discount: 15,
      img: "https://onemg.gumlet.io/a_ignore,w_380,h_380,c_fit,q_auto,f_auto/oxm3yrglzdy06xligskb.jpg",
    },
    {
      isProduct: true,
      title: "Zandu Kesari Jeevan Fit for Diabetics",
      path: "/medicines",
      desc: "jar of 900 gm Paste",
      price: 655,
      discount: 15,
      img: "https://onemg.gumlet.io/a_ignore,w_380,h_380,c_fit,q_auto,f_auto/oxm3yrglzdy06xligskb.jpg",
    },
    {
      isProduct: true,
      title: "Zandu Kesari Jeevan Fit for Diabetics",
      path: "/medicines",
      desc: "jar of 900 gm Paste",
      price: 655,
      discount: 15,
      img: "https://onemg.gumlet.io/a_ignore,w_380,h_380,c_fit,q_auto,f_auto/oxm3yrglzdy06xligskb.jpg",
    },
    {
      isProduct: true,
      title: "Zandu Kesari Jeevan Fit for Diabetics",
      path: "/medicines",
      desc: "jar of 900 gm Paste",
      price: 655,
      discount: 15,
      img: "https://onemg.gumlet.io/a_ignore,w_380,h_380,c_fit,q_auto,f_auto/oxm3yrglzdy06xligskb.jpg",
    },
    {
      isProduct: true,
      title: "Zandu Kesari Jeevan Fit for Diabetics",
      path: "/medicines",
      desc: "jar of 900 gm Paste",
      price: 655,
      discount: 15,
      img: "https://onemg.gumlet.io/a_ignore,w_380,h_380,c_fit,q_auto,f_auto/oxm3yrglzdy06xligskb.jpg",
    },
    {
      isProduct: true,
      title: "Zandu Kesari Jeevan Fit for Diabetics",
      path: "/medicines",
      desc: "jar of 900 gm Paste",
      price: 655,
      discount: 15,
      img: "https://onemg.gumlet.io/a_ignore,w_380,h_380,c_fit,q_auto,f_auto/oxm3yrglzdy06xligskb.jpg",
    },
    {
      isProduct: true,
      title: "Zandu Kesari Jeevan Fit for Diabetics",
      path: "/medicines",
      desc: "jar of 900 gm Paste",
      price: 655,
      discount: 15,
      img: "https://onemg.gumlet.io/a_ignore,w_380,h_380,c_fit,q_auto,f_auto/oxm3yrglzdy06xligskb.jpg",
    },
    {
      isProduct: true,
      title: "Zandu Kesari Jeevan Fit for Diabetics",
      path: "/medicines",
      desc: "jar of 900 gm Paste",
      price: 655,
      discount: 15,
      img: "https://onemg.gumlet.io/a_ignore,w_380,h_380,c_fit,q_auto,f_auto/oxm3yrglzdy06xligskb.jpg",
    },
    {
      isProduct: true,
      title: "Zandu Kesari Jeevan Fit for Diabetics",
      path: "/medicines",
      desc: "jar of 900 gm Paste",
      price: 655,
      discount: 15,
      img: "https://onemg.gumlet.io/a_ignore,w_380,h_380,c_fit,q_auto,f_auto/oxm3yrglzdy06xligskb.jpg",
    },
  ],
  PopularCategories: [
    {
      title: "Diabetes Care",
      path: "/medicines",
      img: "https://onemg.gumlet.io/a_ignore,w_150,h_150,c_fit,q_auto,f_auto/e3katuw3w1qdfiv0cbjn.png",
    },
    {
      title: "Cardiac Care",
      path: "/labTests",
      img: "https://onemg.gumlet.io/a_ignore,w_150,h_150,c_fit,q_auto,f_auto/bal76mxxccyhrti2erkn.png",
    },
    {
      title: "Stomach Care",
      path: "/healthcare",
      img: "https://onemg.gumlet.io/a_ignore,w_150,h_150,c_fit,q_auto,f_auto/l2zrxcsfyguccggnkp4m.png",
    },
    {
      title: "Liver Care",
      path: "/",
      img: "https://onemg.gumlet.io/a_ignore,w_150,h_150,c_fit,q_auto,f_auto/klrkvhzloqbyt6z8cvgv.png",
    },
    {
      title: "Bone, Joint & Muscle Care",
      path: "/",
      img: "https://onemg.gumlet.io/a_ignore,w_150,h_150,c_fit,q_auto,f_auto/zd1jcixlqcmxlxlmgitc.png",
    },
    {
      title: "Kidney Care",
      path: "/offers",
      img: "https://onemg.gumlet.io/a_ignore,w_150,h_150,c_fit,q_auto,f_auto/c0o3w8wdjnzesk2pshcr.png",
    },
    {
      title: "Pain Relief",
      path: "/",
      img: "https://onemg.gumlet.io/a_ignore,w_150,h_150,c_fit,q_auto,f_auto/vsyneobahnsdqzllvzuv.png",
    },
    {
      title: "Respiratory Care",
      path: "/",
      img: "https://onemg.gumlet.io/a_ignore,w_150,h_150,c_fit,q_auto,f_auto/wgixpbxnlrd79lzhpsi3.png",
    },
    {
      title: "Eye Care",
      path: "/",
      img: "https://onemg.gumlet.io/a_ignore,w_150,h_150,c_fit,q_auto,f_auto/laztovaqkws3bo1ywff0.png",
    },
  ],
  PopularComboDeals: [
    {
      isProduct: true,
      title: "Zandu Kesari Jeevan Fit for Diabetics",
      path: "/medicines",
      desc: "jar of 900 gm Paste",
      price: 655,
      discount: 15,
      img: "https://onemg.gumlet.io/a_ignore,w_380,h_380,c_fit,q_auto,f_auto/oxm3yrglzdy06xligskb.jpg",
    },
    {
      isProduct: true,
      title: "Zandu Kesari Jeevan Fit for Diabetics",
      path: "/medicines",
      desc: "jar of 900 gm Paste",
      price: 655,
      discount: 15,
      img: "https://onemg.gumlet.io/a_ignore,w_380,h_380,c_fit,q_auto,f_auto/oxm3yrglzdy06xligskb.jpg",
    },
    {
      isProduct: true,
      title: "Zandu Kesari Jeevan Fit for Diabetics",
      path: "/medicines",
      desc: "jar of 900 gm Paste",
      price: 655,
      discount: 15,
      img: "https://onemg.gumlet.io/a_ignore,w_380,h_380,c_fit,q_auto,f_auto/oxm3yrglzdy06xligskb.jpg",
    },
    {
      isProduct: true,
      title: "Zandu Kesari Jeevan Fit for Diabetics",
      path: "/medicines",
      desc: "jar of 900 gm Paste",
      price: 655,
      discount: 15,
      img: "https://onemg.gumlet.io/a_ignore,w_380,h_380,c_fit,q_auto,f_auto/oxm3yrglzdy06xligskb.jpg",
    },
    {
      isProduct: true,
      title: "Zandu Kesari Jeevan Fit for Diabetics",
      path: "/medicines",
      desc: "jar of 900 gm Paste",
      price: 655,
      discount: 15,
      img: "https://onemg.gumlet.io/a_ignore,w_380,h_380,c_fit,q_auto,f_auto/oxm3yrglzdy06xligskb.jpg",
    },
    {
      isProduct: true,
      title: "Zandu Kesari Jeevan Fit for Diabetics",
      path: "/medicines",
      desc: "jar of 900 gm Paste",
      price: 655,
      discount: 15,
      img: "https://onemg.gumlet.io/a_ignore,w_380,h_380,c_fit,q_auto,f_auto/oxm3yrglzdy06xligskb.jpg",
    },
    {
      isProduct: true,
      title: "Zandu Kesari Jeevan Fit for Diabetics",
      path: "/medicines",
      desc: "jar of 900 gm Paste",
      price: 655,
      discount: 15,
      img: "https://onemg.gumlet.io/a_ignore,w_380,h_380,c_fit,q_auto,f_auto/oxm3yrglzdy06xligskb.jpg",
    },
    {
      isProduct: true,
      title: "Zandu Kesari Jeevan Fit for Diabetics",
      path: "/medicines",
      desc: "jar of 900 gm Paste",
      price: 655,
      discount: 15,
      img: "https://onemg.gumlet.io/a_ignore,w_380,h_380,c_fit,q_auto,f_auto/oxm3yrglzdy06xligskb.jpg",
    },
    {
      isProduct: true,
      title: "Zandu Kesari Jeevan Fit for Diabetics",
      path: "/medicines",
      desc: "jar of 900 gm Paste",
      price: 655,
      discount: 15,
      img: "https://onemg.gumlet.io/a_ignore,w_380,h_380,c_fit,q_auto,f_auto/oxm3yrglzdy06xligskb.jpg",
    },
  ],
  AdultDiapers: [
    {
      isProduct: true,
      title: "Zandu Kesari Jeevan Fit for Diabetics",
      path: "/medicines",
      desc: "jar of 900 gm Paste",
      price: 655,
      discount: 15,
      img: "https://onemg.gumlet.io/a_ignore,w_380,h_380,c_fit,q_auto,f_auto/oxm3yrglzdy06xligskb.jpg",
    },
    {
      isProduct: true,
      title: "Zandu Kesari Jeevan Fit for Diabetics",
      path: "/medicines",
      desc: "jar of 900 gm Paste",
      price: 655,
      discount: 15,
      img: "https://onemg.gumlet.io/a_ignore,w_380,h_380,c_fit,q_auto,f_auto/oxm3yrglzdy06xligskb.jpg",
    },
    {
      isProduct: true,
      title: "Zandu Kesari Jeevan Fit for Diabetics",
      path: "/medicines",
      desc: "jar of 900 gm Paste",
      price: 655,
      discount: 15,
      img: "https://onemg.gumlet.io/a_ignore,w_380,h_380,c_fit,q_auto,f_auto/oxm3yrglzdy06xligskb.jpg",
    },
    {
      isProduct: true,
      title: "Zandu Kesari Jeevan Fit for Diabetics",
      path: "/medicines",
      desc: "jar of 900 gm Paste",
      price: 655,
      discount: 15,
      img: "https://onemg.gumlet.io/a_ignore,w_380,h_380,c_fit,q_auto,f_auto/oxm3yrglzdy06xligskb.jpg",
    },
    {
      isProduct: true,
      title: "Zandu Kesari Jeevan Fit for Diabetics",
      path: "/medicines",
      desc: "jar of 900 gm Paste",
      price: 655,
      discount: 15,
      img: "https://onemg.gumlet.io/a_ignore,w_380,h_380,c_fit,q_auto,f_auto/oxm3yrglzdy06xligskb.jpg",
    },
    {
      isProduct: true,
      title: "Zandu Kesari Jeevan Fit for Diabetics",
      path: "/medicines",
      desc: "jar of 900 gm Paste",
      price: 655,
      discount: 15,
      img: "https://onemg.gumlet.io/a_ignore,w_380,h_380,c_fit,q_auto,f_auto/oxm3yrglzdy06xligskb.jpg",
    },
    {
      isProduct: true,
      title: "Zandu Kesari Jeevan Fit for Diabetics",
      path: "/medicines",
      desc: "jar of 900 gm Paste",
      price: 655,
      discount: 15,
      img: "https://onemg.gumlet.io/a_ignore,w_380,h_380,c_fit,q_auto,f_auto/oxm3yrglzdy06xligskb.jpg",
    },
    {
      isProduct: true,
      title: "Zandu Kesari Jeevan Fit for Diabetics",
      path: "/medicines",
      desc: "jar of 900 gm Paste",
      price: 655,
      discount: 15,
      img: "https://onemg.gumlet.io/a_ignore,w_380,h_380,c_fit,q_auto,f_auto/oxm3yrglzdy06xligskb.jpg",
    },
    {
      isProduct: true,
      title: "Zandu Kesari Jeevan Fit for Diabetics",
      path: "/medicines",
      desc: "jar of 900 gm Paste",
      price: 655,
      discount: 15,
      img: "https://onemg.gumlet.io/a_ignore,w_380,h_380,c_fit,q_auto,f_auto/oxm3yrglzdy06xligskb.jpg",
    },
  ],
  IronSupplementoftheweek: [
    {
      isProduct: true,
      title: "Zandu Kesari Jeevan Fit for Diabetics",
      path: "/medicines",
      desc: "jar of 900 gm Paste",
      price: 655,
      discount: 15,
      img: "https://onemg.gumlet.io/a_ignore,w_380,h_380,c_fit,q_auto,f_auto/oxm3yrglzdy06xligskb.jpg",
    },
    {
      isProduct: true,
      title: "Zandu Kesari Jeevan Fit for Diabetics",
      path: "/medicines",
      desc: "jar of 900 gm Paste",
      price: 655,
      discount: 15,
      img: "https://onemg.gumlet.io/a_ignore,w_380,h_380,c_fit,q_auto,f_auto/oxm3yrglzdy06xligskb.jpg",
    },
    {
      isProduct: true,
      title: "Zandu Kesari Jeevan Fit for Diabetics",
      path: "/medicines",
      desc: "jar of 900 gm Paste",
      price: 655,
      discount: 15,
      img: "https://onemg.gumlet.io/a_ignore,w_380,h_380,c_fit,q_auto,f_auto/oxm3yrglzdy06xligskb.jpg",
    },
    {
      isProduct: true,
      title: "Zandu Kesari Jeevan Fit for Diabetics",
      path: "/medicines",
      desc: "jar of 900 gm Paste",
      price: 655,
      discount: 15,
      img: "https://onemg.gumlet.io/a_ignore,w_380,h_380,c_fit,q_auto,f_auto/oxm3yrglzdy06xligskb.jpg",
    },
    {
      isProduct: true,
      title: "Zandu Kesari Jeevan Fit for Diabetics",
      path: "/medicines",
      desc: "jar of 900 gm Paste",
      price: 655,
      discount: 15,
      img: "https://onemg.gumlet.io/a_ignore,w_380,h_380,c_fit,q_auto,f_auto/oxm3yrglzdy06xligskb.jpg",
    },
    {
      isProduct: true,
      title: "Zandu Kesari Jeevan Fit for Diabetics",
      path: "/medicines",
      desc: "jar of 900 gm Paste",
      price: 655,
      discount: 15,
      img: "https://onemg.gumlet.io/a_ignore,w_380,h_380,c_fit,q_auto,f_auto/oxm3yrglzdy06xligskb.jpg",
    },
    {
      isProduct: true,
      title: "Zandu Kesari Jeevan Fit for Diabetics",
      path: "/medicines",
      desc: "jar of 900 gm Paste",
      price: 655,
      discount: 15,
      img: "https://onemg.gumlet.io/a_ignore,w_380,h_380,c_fit,q_auto,f_auto/oxm3yrglzdy06xligskb.jpg",
    },
    {
      isProduct: true,
      title: "Zandu Kesari Jeevan Fit for Diabetics",
      path: "/medicines",
      desc: "jar of 900 gm Paste",
      price: 655,
      discount: 15,
      img: "https://onemg.gumlet.io/a_ignore,w_380,h_380,c_fit,q_auto,f_auto/oxm3yrglzdy06xligskb.jpg",
    },
    {
      isProduct: true,
      title: "Zandu Kesari Jeevan Fit for Diabetics",
      path: "/medicines",
      desc: "jar of 900 gm Paste",
      price: 655,
      discount: 15,
      img: "https://onemg.gumlet.io/a_ignore,w_380,h_380,c_fit,q_auto,f_auto/oxm3yrglzdy06xligskb.jpg",
    },
  ],
  HEALTHUTSAV: [
    {
      title: "Diabetes Care",
      path: "/medicines",
      img: "https://onemg.gumlet.io/a_ignore,w_150,h_150,c_fit,q_auto,f_auto/e3katuw3w1qdfiv0cbjn.png",
    },
    {
      title: "Cardiac Care",
      path: "/labTests",
      img: "https://onemg.gumlet.io/a_ignore,w_150,h_150,c_fit,q_auto,f_auto/bal76mxxccyhrti2erkn.png",
    },
    {
      title: "Stomach Care",
      path: "/healthcare",
      img: "https://onemg.gumlet.io/a_ignore,w_150,h_150,c_fit,q_auto,f_auto/l2zrxcsfyguccggnkp4m.png",
    },
    {
      title: "Liver Care",
      path: "/",
      img: "https://onemg.gumlet.io/a_ignore,w_150,h_150,c_fit,q_auto,f_auto/klrkvhzloqbyt6z8cvgv.png",
    },
    {
      title: "Bone, Joint & Muscle Care",
      path: "/",
      img: "https://onemg.gumlet.io/a_ignore,w_150,h_150,c_fit,q_auto,f_auto/zd1jcixlqcmxlxlmgitc.png",
    },
    {
      title: "Kidney Care",
      path: "/offers",
      img: "https://onemg.gumlet.io/a_ignore,w_150,h_150,c_fit,q_auto,f_auto/c0o3w8wdjnzesk2pshcr.png",
    },
    {
      title: "Pain Relief",
      path: "/",
      img: "https://onemg.gumlet.io/a_ignore,w_150,h_150,c_fit,q_auto,f_auto/vsyneobahnsdqzllvzuv.png",
    },
    {
      title: "Respiratory Care",
      path: "/",
      img: "https://onemg.gumlet.io/a_ignore,w_150,h_150,c_fit,q_auto,f_auto/wgixpbxnlrd79lzhpsi3.png",
    },
    {
      title: "Eye Care",
      path: "/",
      img: "https://onemg.gumlet.io/a_ignore,w_150,h_150,c_fit,q_auto,f_auto/laztovaqkws3bo1ywff0.png",
    },
  ],
  DiabetesNutrition: [
    {
      isProduct: true,
      title: "Zandu Kesari Jeevan Fit for Diabetics",
      path: "/medicines",
      desc: "jar of 900 gm Paste",
      price: 655,
      discount: 15,
      img: "https://onemg.gumlet.io/a_ignore,w_380,h_380,c_fit,q_auto,f_auto/oxm3yrglzdy06xligskb.jpg",
    },
    {
      isProduct: true,
      title: "Zandu Kesari Jeevan Fit for Diabetics",
      path: "/medicines",
      desc: "jar of 900 gm Paste",
      price: 655,
      discount: 15,
      img: "https://onemg.gumlet.io/a_ignore,w_380,h_380,c_fit,q_auto,f_auto/oxm3yrglzdy06xligskb.jpg",
    },
    {
      isProduct: true,
      title: "Zandu Kesari Jeevan Fit for Diabetics",
      path: "/medicines",
      desc: "jar of 900 gm Paste",
      price: 655,
      discount: 15,
      img: "https://onemg.gumlet.io/a_ignore,w_380,h_380,c_fit,q_auto,f_auto/oxm3yrglzdy06xligskb.jpg",
    },
    {
      isProduct: true,
      title: "Zandu Kesari Jeevan Fit for Diabetics",
      path: "/medicines",
      desc: "jar of 900 gm Paste",
      price: 655,
      discount: 15,
      img: "https://onemg.gumlet.io/a_ignore,w_380,h_380,c_fit,q_auto,f_auto/oxm3yrglzdy06xligskb.jpg",
    },
    {
      isProduct: true,
      title: "Zandu Kesari Jeevan Fit for Diabetics",
      path: "/medicines",
      desc: "jar of 900 gm Paste",
      price: 655,
      discount: 15,
      img: "https://onemg.gumlet.io/a_ignore,w_380,h_380,c_fit,q_auto,f_auto/oxm3yrglzdy06xligskb.jpg",
    },
    {
      isProduct: true,
      title: "Zandu Kesari Jeevan Fit for Diabetics",
      path: "/medicines",
      desc: "jar of 900 gm Paste",
      price: 655,
      discount: 15,
      img: "https://onemg.gumlet.io/a_ignore,w_380,h_380,c_fit,q_auto,f_auto/oxm3yrglzdy06xligskb.jpg",
    },
    {
      isProduct: true,
      title: "Zandu Kesari Jeevan Fit for Diabetics",
      path: "/medicines",
      desc: "jar of 900 gm Paste",
      price: 655,
      discount: 15,
      img: "https://onemg.gumlet.io/a_ignore,w_380,h_380,c_fit,q_auto,f_auto/oxm3yrglzdy06xligskb.jpg",
    },
    {
      isProduct: true,
      title: "Zandu Kesari Jeevan Fit for Diabetics",
      path: "/medicines",
      desc: "jar of 900 gm Paste",
      price: 655,
      discount: 15,
      img: "https://onemg.gumlet.io/a_ignore,w_380,h_380,c_fit,q_auto,f_auto/oxm3yrglzdy06xligskb.jpg",
    },
    {
      isProduct: true,
      title: "Zandu Kesari Jeevan Fit for Diabetics",
      path: "/medicines",
      desc: "jar of 900 gm Paste",
      price: 655,
      discount: 15,
      img: "https://onemg.gumlet.io/a_ignore,w_380,h_380,c_fit,q_auto,f_auto/oxm3yrglzdy06xligskb.jpg",
    },
  ],
  IntheSpotlight: [
    {
      isProduct: true,
      title: "Zandu Kesari Jeevan Fit for Diabetics",
      path: "/medicines",
      desc: "jar of 900 gm Paste",
      price: 655,
      discount: 15,
      img: "https://onemg.gumlet.io/a_ignore,w_380,h_380,c_fit,q_auto,f_auto/oxm3yrglzdy06xligskb.jpg",
    },
    {
      isProduct: true,
      title: "Zandu Kesari Jeevan Fit for Diabetics",
      path: "/medicines",
      desc: "jar of 900 gm Paste",
      price: 655,
      discount: 15,
      img: "https://onemg.gumlet.io/a_ignore,w_380,h_380,c_fit,q_auto,f_auto/oxm3yrglzdy06xligskb.jpg",
    },
    {
      isProduct: true,
      title: "Zandu Kesari Jeevan Fit for Diabetics",
      path: "/medicines",
      desc: "jar of 900 gm Paste",
      price: 655,
      discount: 15,
      img: "https://onemg.gumlet.io/a_ignore,w_380,h_380,c_fit,q_auto,f_auto/oxm3yrglzdy06xligskb.jpg",
    },
    {
      isProduct: true,
      title: "Zandu Kesari Jeevan Fit for Diabetics",
      path: "/medicines",
      desc: "jar of 900 gm Paste",
      price: 655,
      discount: 15,
      img: "https://onemg.gumlet.io/a_ignore,w_380,h_380,c_fit,q_auto,f_auto/oxm3yrglzdy06xligskb.jpg",
    },
    {
      isProduct: true,
      title: "Zandu Kesari Jeevan Fit for Diabetics",
      path: "/medicines",
      desc: "jar of 900 gm Paste",
      price: 655,
      discount: 15,
      img: "https://onemg.gumlet.io/a_ignore,w_380,h_380,c_fit,q_auto,f_auto/oxm3yrglzdy06xligskb.jpg",
    },
    {
      isProduct: true,
      title: "Zandu Kesari Jeevan Fit for Diabetics",
      path: "/medicines",
      desc: "jar of 900 gm Paste",
      price: 655,
      discount: 15,
      img: "https://onemg.gumlet.io/a_ignore,w_380,h_380,c_fit,q_auto,f_auto/oxm3yrglzdy06xligskb.jpg",
    },
    {
      isProduct: true,
      title: "Zandu Kesari Jeevan Fit for Diabetics",
      path: "/medicines",
      desc: "jar of 900 gm Paste",
      price: 655,
      discount: 15,
      img: "https://onemg.gumlet.io/a_ignore,w_380,h_380,c_fit,q_auto,f_auto/oxm3yrglzdy06xligskb.jpg",
    },
    {
      isProduct: true,
      title: "Zandu Kesari Jeevan Fit for Diabetics",
      path: "/medicines",
      desc: "jar of 900 gm Paste",
      price: 655,
      discount: 15,
      img: "https://onemg.gumlet.io/a_ignore,w_380,h_380,c_fit,q_auto,f_auto/oxm3yrglzdy06xligskb.jpg",
    },
    {
      isProduct: true,
      title: "Zandu Kesari Jeevan Fit for Diabetics",
      path: "/medicines",
      desc: "jar of 900 gm Paste",
      price: 655,
      discount: 15,
      img: "https://onemg.gumlet.io/a_ignore,w_380,h_380,c_fit,q_auto,f_auto/oxm3yrglzdy06xligskb.jpg",
    },
  ],
};
